version: 0.0
os: linux
files:
  - source: .
    destination: /home/sst/apps/seedlot-selection-tool
permissions:
  - object: .
    owner: sst
    group: sst
hooks:
  AfterInstall:
    - location: CodeDeploy/AfterInstall.sh
      runas: seedsource
    - location: CodeDeploy/AfterInstall-root.sh
      runas: root
