version: 0.0
os: linux
files:
  - source: .
    destination: /home/sst/build
permissions:
  - object: .
    owner: sst
    group: sst
hooks:
  BeforeInstall:
    - location: CodeDeploy/BeforeInstall.sh
      runas: sst
  AfterInstall:
    - location: CodeDeploy/AfterInstall.sh
      runas: root
