version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - source ~/.bashrc
      - git clone https://github.com/consbio/seedlot-selection-tool.git sst-build
      - (cd sst-build/ && git checkout master && git submodule update --init)
      - (cd sst-build/javascript && pnpm install)
  build:
    commands:
      - (cd sst-build/javascript && pnpm extract-messages && pnpm build)

artifacts:
  files: '**/*'
  base-directory: 'sst-build'
