version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/consbio/seedlot-selection-tool.git sst-build
      - (cd sst-build/ && git checkout master && git submodule update --init)
      - (cd sst-build/javascript && yarn install)
  build:
    commands:
      - (cd sst-build/javascript && yarn run merge-messages && yarn run build)

artifacts:
  files: "**/*"
  base-directory: "sst-build"
