version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/consbio/seedlot-selection-tool.git sst-build
      - (cd sst-build/ && git checkout ${CODEBUILD_SOURCE_REPO_URL} && git submodule update --init)
      - (cd sst-build/javascript && npm install)
      - (cd sst-build/seedsource-core/javascript && npm install)
  build:
    commands:
      - (cd sst-build/javascript && npm run-script build)

artifacts:
  files: "**/*"
  base-directory: "sst-build"
