=== Step 2. Select Location

You can either enter coordinates or click on the map to indicate the location of your seedlot or planting site. The
location of a seedlot represents the geographic location where it is best adapted—that is, the center of its adaptive
climate space.

==== Enter your location as coordinates

You can enter the latitude and longitude of your location in decimal degrees. (Note: enter a negative value for a
longitude in North America.)

==== Use the map to select your location

Alternatively, use the pan and zoom tools to navigate to your area of interest, and then click on the map. This will
show the latitude, longitude, and elevation of your location, as well as any seed or breeding zones associated with
that location. If you click on the *Set Point* button, your current coordinates and other location information will be
automatically set for use by the program. If you have already selected climate variables in Step 6, it will also show
their values.

.Optional
[NOTE]
====
You can map multiple seedlots for comparison to a planting site, or multiple planting sites for comparison to a
seedlot, by clicking on the *Add Seedlots* or the *Add Planting Sites* button, respectively. After clicking on the
button, you can either enter the coordinates of each location or click on the map. Be sure to click on the *Add* button
or you could inadvertently shift the initial location to which you are comparing seedlots or planting sites. After
running the tool, a similarity index is calculated between the initial planting site or seedlot and the locations to be
compared to it (see Step 8 for details).

_(Under construction: (1) Calculating climatic transfer distances for each climate variable for each location. (2)
Ability to enter a batch of locations. (3) Ability to output a table showing the results of all the comparisons.)_
====
