---
- name: Deploy code
  hosts: webservers
  tasks:
    - name: Synchronize code with server
      become: true
      become_user: sst
      ansible.posix.synchronize:
        src: ../../
        dest: /home/sst/apps/seedlot-selection-tool/
        recursive: true
        delete: true
        rsync_opts:
          - "--filter='+ javascript/build/'"
          - "--filter='+ webpack-stats.json'"
          - "--filter=':- .gitignore'"
          - '--exclude=.git'
          - '--exclude=.idea'
