# Generated by Django 3.2.16 on 2022-10-19 17:08

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('seedsource', '0001_initial'), ('seedsource', '0002_auto_20181207_0937'), ('seedsource', '0003_transferlimit_label'), ('seedsource', '0004_auto_20181209_0658'), ('seedsource', '0005_transferlimit_elevation'), ('seedsource', '0006_auto_20201005_2121'), ('seedsource', '0007_zonesource_order'), ('seedsource', '0008_auto_20201201_1443'), ('seedsource', '0009_runconfiguration_version'), ('seedsource', '0010_shareurl'), ('seedsource', '0011_alter_shareurl_configuration'), ('seedsource', '0012_auto_20221010_1841')]

    initial = True

    dependencies = [
        ('ncdjango', '0003_auto_20151230_0954'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=10)),
                ('zone_id', models.CharField(max_length=100, null=True)),
                ('zone_uid', models.CharField(max_length=50, null=True, unique=True)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('zone_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seedsource.zonesource')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('polygons', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RunConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('configuration', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'index_together': {('owner', 'title'), ('owner', 'created')},
            },
        ),
        migrations.CreateModel(
            name='ShareURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=8, unique=True)),
                ('configuration', models.JSONField()),
                ('version', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accessed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=10)),
                ('time_period', models.CharField(max_length=10)),
                ('low', models.IntegerField(null=True)),
                ('high', models.IntegerField(null=True)),
                ('transfer', models.FloatField()),
                ('avg_transfer', models.FloatField(default=0)),
                ('center', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seedsource.seedzone')),
                ('label', models.CharField(max_length=100, null=True)),
                ('elevation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncdjango.service')),
            ],
        ),
    ]
