# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 17:17
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('polygons', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('configuration', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeedZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=10)),
                ('zone_id', models.IntegerField(null=True)),
                ('zone_uid', models.CharField(max_length=50, null=True, unique=True)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                ('bands_fn', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=10)),
                ('time_period', models.CharField(max_length=10)),
                ('low', models.IntegerField(null=True)),
                ('high', models.IntegerField(null=True)),
                ('transfer', models.FloatField()),
                ('avg_transfer', models.FloatField(default=0)),
                ('center', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seedsource.SeedZone')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='runconfiguration',
            index_together=set([('owner', 'title'), ('owner', 'created')]),
        ),
    ]
