# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0002_auto_20181207_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlimit',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
