# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0003_transferlimit_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedzone',
            name='zone_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
