# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncdjango', '0003_auto_20151230_0954'),
        ('seedsource', '0004_auto_20181209_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlimit',
            name='elevation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncdjango.Service'),
        ),
    ]
