# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0006_auto_20201005_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonesource',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
