# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-01 22:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0007_zonesource_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedzone',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
