# Generated by Django 2.2.25 on 2022-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0008_auto_20201201_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='runconfiguration',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
