# Generated by Django 2.2.25 on 2022-03-21 18:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0009_runconfiguration_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=8, unique=True)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField()),
                ('version', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accessed', models.DateTimeField(null=True)),
            ],
        ),
    ]
