# Generated by Django 3.2.16 on 2022-10-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0010_shareurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareurl',
            name='configuration',
            field=models.JSONField(),
        ),
    ]
