# Generated by Django 5.2.2 on 2025-09-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedsource', '0001_squashed_0012_auto_20221010_1841'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='runconfiguration',
            new_name='seedsource__owner_i_fdbbf8_idx',
            old_fields=('owner', 'created'),
        ),
        migrations.RenameIndex(
            model_name='runconfiguration',
            new_name='seedsource__owner_i_db0466_idx',
            old_fields=('owner', 'title'),
        ),
    ]
