# Generated by Django 5.2.6 on 2025-10-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "seedsource",
            "0013_rename_runconfiguration_owner_created_seedsource__owner_i_fdbbf8_idx_and_more",
        ),
        (
            "seedsource",
            "0013_rename_runconfiguration_owner_title_seedsource__owner_i_db0466_idx_and_more",
        ),
    ]

    operations = []
