=== Paso 8. Mapear sus resultados

Haga clic en “Ejecutar herramienta” para producir un mapa que muestre en dónde puede encontrar lotes de semillas o sitios de plantación adecuados para las ubicaciones especificadas en el Paso 2 y el clima del periodo especificado en el Paso 4. El mapa muestra el grado de coincidencia entre el clima del pasado al que está adaptado un lote de semillas y el clima del periodo en el que se espera que los árboles se adapten mejor al sitio de plantación. El naranja más oscuro indica la mejor coincidencia; el naranja más claro indica la coincidencia que está en el borde del límite de transferencia. Tenga en cuenta que el uso de un límite de transferencia más grande no afecta la mejor coincidencia, pero da como resultado un área geográfica de adecuación más amplia.

El proceso para determinar el grado de coincidencia es, en primer lugar, reescalar los datos de la cuadrícula para cada variable climática (o rasgo asociado de una función de genecología) como: latexmath:[y = \frac{|x - xmid|}{TL}], donde 'xmid' es el valor del punto medio o centro climático. En segundo lugar, la distancia climática multivariante ('d') desde el centro climático hasta cada punto de la cuadrícula se calcula como la distancia euclidiana para 'n' variables climáticas: latexmath:[dn = ({y_1}^2 + {y_2}^2 + ... + {y_n}^2)0.5]. Finalmente, la coincidencia climática ('m') (también llamada índice de similitud en el Paso 2) se calcula como latexmath:[m = -(d-1)*100]. Los valores de latexmath:[m < 0] no se asignan, mientras que los valores entre '0' y '100' se asignan utilizando la escala de colores que va del naranja claro al naranja oscuro.

Tenga en cuenta que puede usar la barra deslizante del lado derecho para ver mejor el mapa subyacente de la información de coincidencia climática proporcionada.

Si configuró una cuenta y está registrado, puede guardar sus entradas haciendo clic en el botón “Save Last Run” (Guardar última ejecución). Se le pedirá que indique un nombre para la ejecución guardada. Una vez guardada, la ejecución aparecerá en la ventana de “Saved Runs” (Ejecuciones guardadas) (ver a continuación).

También puede exportar los resultados a un archivo PDF, PowerPoint o GeoTIFF haciendo clic en el botón “Expor As…” (Exporta como). Otra opción es usar la tecla “Print Scrn” (Impr. pant.) del teclado para hacer una copia de la pantalla que es posible pegar en otro archivo, como por ejemplo, una presentación de PowerPoint.
